config/routes.rb
SamlAuth::Application.routes.draw do

  resources :stuffs

  namespace :admin do 
    resources :accounts 
    resources :settings
  end
  root :to => "stuffs#index"
  match "saml" => "saml#index"
  match "saml/:action", :controller => "saml"  

end

app/models/admin/account.rb
class Admin::Account < ActiveRecord::Base
  #has_one :setting, :dependent => :destroy
  belongs_to :setting
  accepts_nested_attributes_for :setting
  #attr_accessor :id

  
  # Internal getter for other controllers.  If host is not given
  # look it up using the request
  def self.get_saml_settings(host)
    # Grab the ActiveRecord Setting object from the Account
    setting_AR = Admin::Account.find(:all, :conditions => { :host => host } ).first
    return nil if setting_AR == nil

    setting_AR = setting_AR.setting

    # Create a new Onelogin version of the similarly defined class
    setting_SAML = Onelogin::Saml::Settings.new

    # And copy those settings into the Onelogin object for use in the rest of the Onelogin namespace
    # (I'm guessing there's probably a better way to do this!)
    if setting_AR.assertion_consumer_service_url != nil
      setting_SAML.assertion_consumer_service_url = setting_AR.assertion_consumer_service_url
    end
    if setting_AR.assertion_consumer_service_binding != nil
      setting_SAML.assertion_consumer_service_binding = setting_AR.assertion_consumer_service_binding
    end
    if setting_AR.single_logout_service_url != nil
      setting_SAML.single_logout_service_url = setting_AR.single_logout_service_url
    end
    if setting_AR.single_logout_service_binding != nil
      setting_SAML.single_logout_service_binding = setting_AR.single_logout_service_binding
    end
    if setting_AR.issuer != nil
      setting_SAML.issuer = setting_AR.issuer
    end
    if setting_AR.idp_sso_target_url != ""
      setting_SAML.idp_sso_target_url = setting_AR.idp_sso_target_url
    end
    if setting_AR.idp_cert_fingerprint != ""
      setting_SAML.idp_cert_fingerprint = setting_AR.idp_cert_fingerprint
    end
    if setting_AR.name_identifier_format != ""
      setting_SAML.name_identifier_format = setting_AR.name_identifier_format
    end
    if setting_AR.authn_context != ""
      setting_SAML.authn_context = setting_AR.authn_context
    end
    if setting_AR.idp_metadata != ""
      setting_SAML.idp_metadata = setting_AR.idp_metadata
    end
    if setting_AR.idp_metadata_ttl != nil
      setting_SAML.idp_metadata_ttl = setting_AR.idp_metadata_ttl
    end

    # return the Onelogin version of the Settings object
    return setting_SAML
  end   

end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::BaseController
  # GET /admin/accounts
  # GET /admin/accounts.json
  def index
    @admin_accounts = Admin::Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @admin_accounts }
    end
  end

  # GET /admin/accounts/1
  # GET /admin/accounts/1.json
  def show
    @admin_account = Admin::Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @admin_account }
    end
  end

  # GET /admin/accounts/new
  # GET /admin/accounts/new.json
  def new
    @admin_account = Admin::Account.new
    @admin_account.build_setting
    @admin_account.setting.assertion_consumer_service_url = request.scheme + "://" + request.host + "/saml/consume"
    @admin_account.setting.single_logout_service_url = request.scheme + "://" + request.host + "/saml/logout"
    @admin_account.setting.name_identifier_format = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
    @admin_account.setting.issuer = request.scheme + "://" + request.host

    #@admin_account.setting = Admin::Setting.new 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @admin_account }
    end
  end

  # GET /admin/accounts/1/edit
  def edit
    @admin_account = Admin::Account.find(params[:id])
  end

  # POST /admin/accounts
  # POST /admin/accounts.json
  def create
    @admin_account = Admin::Account.new(params[:admin_account])

    respond_to do |format|
      if @admin_account.save
        format.html { redirect_to @admin_account, :notice => 'Account was successfully created.' }
        format.json { render :json => @admin_account, :status => :created, :location => @admin_account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @admin_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/accounts/1
  # PUT /admin/accounts/1.json
  def update
    @admin_account = Admin::Account.find(params[:id])

    respond_to do |format|
      if @admin_account.update_attributes(params[:admin_account])
        format.html { redirect_to @admin_account, :notice => 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @admin_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/accounts/1
  # DELETE /admin/accounts/1.json
  def destroy
    @admin_account = Admin::Account.find(params[:id])
    @admin_account.destroy

    respond_to do |format|
      format.html { redirect_to admin_accounts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin/accounts_helper.rb
module Admin::AccountsHelper
end

app/views/admin/accounts/_form.html.erb
<%= form_for(@admin_account) do |f| %>
  <% if @admin_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_account.errors.count, "error") %> prohibited this admin_account from being saved:</h2>

      <ul>
      <% @admin_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host, "Virtual Host Name"
   %><br />
    <%= f.text_field :host, { :value => request.host, :class => "qtip",
    :tooltip => "Enter the name of the SP domain name that will be " +
    " associated with the IdP.<br>Rails request.host must match this" +
    " to look up this account."
  } 
    %>
  </div>
  <div class="field">
    <%= f.label :idle_timeout %><br />
    <%= f.number_field :idle_timeout, { :class => "qtip",
    :tooltip => "Not used for now, just playing around" }
   %>
  </div>
  <div class="field">
    <%= f.label :session_timeout %><br />
    <%= f.number_field :session_timeout, { :class => "qtip",
    :tooltip => "Not used for now, just playing around" }
   %>
  </div>
  <%# @admin_setting = Admin::Setting.new %>
  <%#= render :partial => "admin/settings/form_fields", :locals => { :f => f } %>
  <%= f.fields_for :setting do |builder| %>
    <%= render :partial => "admin/settings/form_fields", :locals => { :f => builder } %>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/accounts/edit.html.erb
<h1>Editing admin_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_account %> |
<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/index.html.erb
<h1>Listing admin_accounts</h1>

<table>
  <tr>
    <th>Host</th>
    <th>Idle timeout</th>
    <th>Session timeout</th>
    <th>Settings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_accounts.each do |admin_account| %>
  <tr>
    <td><%= admin_account.host %></td>
    <td><%= admin_account.idle_timeout %></td>
    <td><%= admin_account.session_timeout %></td>
    <td><%= link_to 'View', admin_setting_path(admin_account.setting) %></td>
    <td><%= link_to 'Show', admin_account %></td>
    <td><%= link_to 'Edit', edit_admin_account_path(admin_account) %></td>
    <td><%= link_to 'Destroy', admin_account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_admin_account_path %>

app/views/admin/accounts/new.html.erb
<h1>New admin_account</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_accounts_path %>

app/views/admin/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Host:</b>
  <%= @admin_account.host %>
</p>

<p>
  <b>Idle timeout:</b>
  <%= @admin_account.idle_timeout %>
</p>

<p>
  <b>Session timeout:</b>
  <%= @admin_account.session_timeout %>
</p>

<p>
  <b>Setting:</b>
  <%= @admin_account.setting %>
</p>


<%= link_to 'Edit', edit_admin_account_path(@admin_account) %> |
<%= link_to 'Back', admin_accounts_path %>