config/routes.rb
SamlAuth::Application.routes.draw do

  resources :stuffs

  namespace :admin do 
    resources :accounts 
    resources :settings
  end
  root :to => "stuffs#index"
  match "saml" => "saml#index"
  match "saml/:action", :controller => "saml"  

end

app/models/stuff.rb
class Stuff < ActiveRecord::Base
end

app/controllers/stuffs_controller.rb
# This is just an example scaffold to show how 
# the authentication hooks should work in your application.

class StuffsController < ApplicationController
  #  The before_filter calls authenticate below.  
  # Uncomment to force authentication for the entire Stuff controller
  #before_filter :authenticate
  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = Stuff.all
    # Look up the settings object to provide a log out link in the view
    @settings = Admin::Account.get_saml_settings( request.host )

    if @settings.nil?
      return redirect_to '/saml'
    end

    # If we're viewing this unauthenticated, set our goback URL for after logging in
    if session[:userid].nil?
      session[:goback_to] = request.url
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @stuffs }
    end
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
    @stuff = Stuff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @stuff }
    end
  end

  # GET /stuffs/new
  # GET /stuffs/new.json
  def new
    @stuff = Stuff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @stuff }
    end
  end

  # GET /stuffs/1/edit
  def edit
    @stuff = Stuff.find(params[:id])
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(params[:stuff])

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to @stuff, :notice => 'Stuff was successfully created.' }
        format.json { render :json => @stuff, :status => :created, :location => @stuff }
      else
        format.html { render :action => "new" }
        format.json { render :json => @stuff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stuffs/1
  # PUT /stuffs/1.json
  def update
    @stuff = Stuff.find(params[:id])

    respond_to do |format|
      if @stuff.update_attributes(params[:stuff])
        format.html { redirect_to @stuff, :notice => 'Stuff was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @stuff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    @stuff = Stuff.find(params[:id])
    @stuff.destroy

    respond_to do |format|
      format.html { redirect_to stuffs_url }
      format.json { head :ok }
    end
  end

  private

  def authenticate
    unless logged_in?
      # Save our current path in the session to return back to
      # after logging in.  (Saml controller looks for this)
      logger.info "Goback URL is '#{request.url}'"
      session[:goback_to] = request.url
      redirect_to saml_url
    end
  end

  def logged_in?
    return false if session[:userid].nil?
    return false if session[:userid] == ""
    return true
  end
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/stuffs/_form.html.erb
<%= form_for(@stuff) do |f| %>
  <% if @stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stuff.errors.count, "error") %> prohibited this stuff from being saved:</h2>

      <ul>
      <% @stuff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stuffs/edit.html.erb
<h1>Editing stuff</h1>

<%= render 'form' %>

<%= link_to 'Show', @stuff %> |
<%= link_to 'Back', stuffs_path %>

app/views/stuffs/index.html.erb
<h1>Listing some stuff</h1>
<br>
<% if session[:attributes] != nil %>
  Logged in as: "<%= session[:userid] %>" <br>
   <br>With attributes: <br>
     <% session[:attributes].each do |name, value| %>
  <%= name %> = <%= value %><br>
     <% end %>
  <br>
   <%= link_to 'Log Out', @settings.single_logout_service_url %>
<% else %>
  Not logged in.  <br><br>
   <%= link_to 'Log In', '/saml' %>
<% end %>
<br>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stuffs.each do |stuff| %>
  <tr>
    <td><%= link_to 'Show', stuff %></td>
    <td><%= link_to 'Edit', edit_stuff_path(stuff) %></td>
    <td><%= link_to 'Destroy', stuff, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stuff', new_stuff_path %>

app/views/stuffs/new.html.erb
<h1>New stuff</h1>

<%= render 'form' %>

<%= link_to 'Back', stuffs_path %>

app/views/stuffs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_stuff_path(@stuff) %> |
<%= link_to 'Back', stuffs_path %>