config/routes.rb
SamlAuth::Application.routes.draw do

  resources :stuffs

  namespace :admin do 
    resources :accounts 
    resources :settings
  end
  root :to => "stuffs#index"
  match "saml" => "saml#index"
  match "saml/:action", :controller => "saml"  

end

app/models/admin/setting.rb
class Admin::Setting < ActiveRecord::Base
  #belongs_to :admin_account
  #belongs_to :account
  has_one :account
  #accepts_nested_attributes_for :admin_account
  
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController
  # GET /admin/settings
  # GET /admin/settings.json
  def index
    @admin_settings = Admin::Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @admin_settings }
    end
  end

  # GET /admin/settings/1
  # GET /admin/settings/1.json
  def show
    @admin_setting = Admin::Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @admin_setting }
    end
  end

  # GET /admin/settings/new
  # GET /admin/settings/new.json
  def new
    @admin_setting = Admin::Setting.new
    @admin_setting.name_identifier_format = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
    @admin_setting.issuer = request.scheme + "://" + request.host
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @admin_setting }
    end
  end

  # GET /admin/settings/1/edit
  def edit
    @admin_setting = Admin::Setting.find(params[:id])
  end

  # POST /admin/settings
  # POST /admin/settings.json
  def create
    @admin_setting = Admin::Setting.new(params[:admin_setting])

    respond_to do |format|
      if @admin_setting.save
        format.html { redirect_to @admin_setting, :notice => 'Setting was successfully created.' }
        format.json { render :json => @admin_setting, :status => :created, :location => @admin_setting }
      else
        format.html { render :action => "new" }
        format.json { render :json => @admin_setting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/settings/1
  # PUT /admin/settings/1.json
  def update
    @admin_setting = Admin::Setting.find(params[:id])

    respond_to do |format|
      if @admin_setting.update_attributes(params[:admin_setting])
        format.html { redirect_to @admin_setting, :notice => 'Setting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @admin_setting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/settings/1
  # DELETE /admin/settings/1.json
  def destroy
    @admin_setting = Admin::Setting.find(params[:id])
    @admin_setting.destroy

    respond_to do |format|
      format.html { redirect_to admin_settings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_form.html.erb
<%= form_for(@admin_setting) do |f| %>
  <% if @admin_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_setting.errors.count, "error") %> prohibited this admin_setting from being saved:</h2>

      <ul>
      <% @admin_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => "/admin/settings/form_fields", :locals => { :f => f } %>

  <% if defined?(do_submit) && do_submit == false %>
  <% else %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
<% end %>

app/views/admin/settings/_form_fields.html.erb
<%# %>
  <div class="field">
    <%= f.label :assertion_consumer_service_url, "Assertion Consumer Service URL" %><br />
    <%= f.text_field :assertion_consumer_service_url, { :class => "qtip", 
    :tooltip => "The ACS URL tells the IdP where to direct back to after" +
    " authentication has succeeded.  Uses Binding Method below",
    :size => 50
   } %>
  </div>
  <br>
  <div class="field">
    <%= f.label :assertion_consumer_service_binding, "Assertion Consumer Service Binding Method" %><br />
    <%= f.select( 
  :assertion_consumer_service_binding,
  [  
    "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
    "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
  ],
  {},{ :class => "qtip",
    :tooltip => "The ACS binding tells the IdP what type of request to make " + 
    "at the ACS URL.  HTTP-Redirect means a GET request.  SOAP and Artifact " +
    "are part of the protocol, but not implemented in ruby-saml (yet)"
  }
       )
     %>
  </div>
  <br>
  <div class="field">
    <%= f.label :single_logout_service_url, "Single Logout Service URL" %><br />
    <%= f.text_field :single_logout_service_url, { :class => "qtip",
                :tooltip => "The SLO URL tells the IdP where to direct to for" +
                " Logout requests and responses.  Uses Binding Method below",
                :size => 50
         } %>
  </div>
        <br>
  <div class="field">
    <%= f.label :single_logout_service_binding, "Single Logout Service Binding Method" %><br />
    <%= f.select(
        :single_logout_service_binding,
        [
                "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
                "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        ],
        {},{ :class => "qtip",
                :tooltip => "The SLO binding tells the IdP what type of request to make " +
                "at the SLO URL.  HTTP-Redirect means a GET request.  SOAP and Artifact " +
                "are part of the protocol, but not implemented in ruby-saml (yet)"
        }
       )
     %>
  </div>
        <br>
  <div class="field">
    <%= f.label :idp_metadata, "IdP Metadata URL or local file" %><br />
    <%= f.text_field :idp_metadata, { :size => 50, :class => "qtip",
    :tooltip => "URL that points at the IdP's metadata.  This should return XML." +
    "  You can also specify a local file if you can't do a remote call. (See caching TTL)"
  } %>
  </div>
  <br>

  <div class="field">
    <%= f.label :idp_metadata_ttl, "IdP Metdata TTL (optonal)" %><br />
    <%= f.number_field :idp_metadata_ttl, { :class => "qtip",
    :tooltip => "Time To Live in seconds that we consider the IdP metadata to be fresh." +
    " Default is 86400 (1 day).  If you need to force a refresh just restart Rails."
  } %>
  </div>
  <br>
  <div class="field">
    <%= f.label :name_identifier_format, "Name Identifier Format" %><br />
    <%= f.text_field :name_identifier_format, {  :size => 50,
    :class => "qtip",
    :tooltip => "NameID format.  Most IdPs use transient, but check with the IdP admin or " +
    "look at the IdP metdata.  The supported NameID formats should be in there."
  }%>
  </div>
  <br>
  <div class="field">
    <%= f.label :issuer, "Issuer (your entity ID)" %><br />
    <%= f.text_field :issuer, {  :size => 50,
    :class => "qtip",
    :tooltip => "The Entity ID is a name that associates the SP to the IdP.  Some IdP's " + 
    "might have special behavior triggerd by this name, like redirecting to it as a URL " +
    "under some horrible failure condition.  Most IdPs use this string to configure permissions too."
  } %>
  </div>
  <br>
  <div class="field">
    <%= f.label :authn_context, "IdP Authn Context (optional)" %><br />
    <%= f.text_field :authn_context, {
    :size => 50,
    :class => "qtip",
    :tooltip => "This forces in an Authn Context, which tells the IdP what method you " +
    "want to use to authenticate.  Most IdPs probably don't need this because they choose " +
    "what methods a user will authenticate with."
  } %>
  </div>
  <br>
  <div class="field">
    <%= f.label :idp_cert_fingerprint, "IdP Cert Fingerprint (not needed with metadata)" %><br />
    <%= f.text_field :idp_cert_fingerprint %>
  </div>
  <br>
  <div class="field">
    <%= f.label :idp_sso_target_url, "IdP SSO Target URL (not needed with metadata)" %><br />
    <%= f.text_field :idp_sso_target_url %>
  </div>
  <br>

app/views/admin/settings/edit.html.erb
<h1>Editing admin_setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_setting %> |
<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/index.html.erb
<h1>Listing admin_settings</h1>

<table>
  <tr>
    <th>Assertion consumer service url</th>
    <th>Assertion consumer service binding</th>
    <th>Single Logout service url</th>
    <th>Single Logout service binding</th>
    <th>Idp metadata</th>
    <th>Idp metadata ttl</th>
    <th>Name identifier format</th>
    <th>Issuer</th>
    <th>Authn context</th>
    <th>Idp cert fingerprint</th>
    <th>Idp sso target url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_settings.each do |admin_setting| %>
  <tr>
    <td><%= admin_setting.assertion_consumer_service_url %></td>
    <td><%= admin_setting.assertion_consumer_service_binding %></td>
    <td><%= admin_setting.single_logout_service_url %></td>
    <td><%= admin_setting.single_logout_service_binding %></td>
    <td><%= admin_setting.idp_metadata %></td>
    <td><%= admin_setting.idp_metadata_ttl %></td>
    <td><%= admin_setting.name_identifier_format %></td>
    <td><%= admin_setting.issuer %></td>
    <td><%= admin_setting.authn_context %></td>
    <td><%= admin_setting.idp_cert_fingerprint %></td>
    <td><%= admin_setting.idp_sso_target_url %></td>
    <td><%= link_to 'Show', admin_setting %></td>
    <td><%= link_to 'Edit', edit_admin_setting_path(admin_setting) %></td>
    <td><%= link_to 'Destroy', admin_setting, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Setting', new_admin_setting_path %>

app/views/admin/settings/new.html.erb
<h1>New admin_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assertion consumer service url:</b>
  <%= @admin_setting.assertion_consumer_service_url %>
</p>

<p>
  <b>Assertion consumer service binding:</b>
  <%= @admin_setting.assertion_consumer_service_binding %>
</p>

<p>
  <b>Single Logout service url:</b>
  <%= @admin_setting.single_logout_service_url %>
</p>

<p>
  <b>Single Logout service binding:</b>
  <%= @admin_setting.single_logout_service_binding %>
</p>

<p>
  <b>Idp metadata:</b>
  <%= @admin_setting.idp_metadata %>
</p>

<p>
  <b>Idp metadata ttl:</b>
  <%= @admin_setting.idp_metadata_ttl %>
</p>

<p>
  <b>Name identifier format:</b>
  <%= @admin_setting.name_identifier_format %>
</p>

<p>
  <b>Issuer:</b>
  <%= @admin_setting.issuer %>
</p>

<p>
  <b>Authn context:</b>
  <%= @admin_setting.authn_context %>
</p>

<p>
  <b>Idp cert fingerprint:</b>
  <%= @admin_setting.idp_cert_fingerprint %>
</p>

<p>
  <b>Idp sso target url:</b>
  <%= @admin_setting.idp_sso_target_url %>
</p>


<%= link_to 'Edit', edit_admin_setting_path(@admin_setting) %> |
<%= link_to 'Back', admin_settings_path %>